"""
Simple script to help set up LLM API keys for the RAG bot
"""
import os
from pathlib import Path

def setup_llm():
    """Interactive setup for LLM API keys"""
    print("=" * 60)
    print("🤖 LLM Setup for RAG Bot")
    print("=" * 60)
    print()
    
    env_file = Path(".env")
    
    # Check if .env already exists
    existing_keys = {}
    if env_file.exists():
        print("📄 Found existing .env file")
        with open(env_file, 'r') as f:
            for line in f:
                if '=' in line and not line.strip().startswith('#'):
                    key, value = line.strip().split('=', 1)
                    if value and value != f"your-{key.lower().replace('_', '-')}-here":
                        existing_keys[key] = value
                        print(f"   ✓ {key} is already set")
        print()
    
    # Setup OpenAI
    print("Option 1: OpenAI (Recommended)")
    print("-" * 60)
    if 'OPENAI_API_KEY' in existing_keys:
        print(f"✓ OpenAI key already configured")
        change = input("   Change it? (y/n): ").lower().strip()
        if change != 'y':
            openai_key = existing_keys['OPENAI_API_KEY']
        else:
            openai_key = input("   Enter your OpenAI API key (starts with sk-): ").strip()
    else:
        print("Get your API key from: https://platform.openai.com/api-keys")
        openai_key = input("Enter your OpenAI API key (or press Enter to skip): ").strip()
    
    print()
    
    # Setup Hugging Face
    print("Option 2: Hugging Face (Free Alternative)")
    print("-" * 60)
    if 'HUGGINGFACE_API_KEY' in existing_keys:
        print(f"✓ Hugging Face key already configured")
        change = input("   Change it? (y/n): ").lower().strip()
        if change != 'y':
            hf_key = existing_keys['HUGGINGFACE_API_KEY']
        else:
            hf_key = input("   Enter your Hugging Face token (starts with hf_): ").strip()
    else:
        print("Get your token from: https://huggingface.co/settings/tokens")
        hf_key = input("Enter your Hugging Face token (or press Enter to skip): ").strip()
    
    print()
    
    # Write to .env file
    print("=" * 60)
    print("💾 Saving configuration...")
    
    lines = []
    if openai_key:
        lines.append(f"OPENAI_API_KEY={openai_key}\n")
    if hf_key:
        lines.append(f"HUGGINGFACE_API_KEY={hf_key}\n")
    
    if lines:
        with open(env_file, 'w') as f:
            f.write("# LLM API Keys\n")
            f.write("# Generated by setup_llm.py\n\n")
            for line in lines:
                f.write(line)
        
        print("✅ Configuration saved to .env file!")
        print()
        print("📋 Summary:")
        if openai_key:
            print(f"   ✓ OpenAI: Configured (key: {openai_key[:10]}...)")
        if hf_key:
            print(f"   ✓ Hugging Face: Configured (token: {hf_key[:10]}...)")
        print()
        print("🚀 Next steps:")
        print("   1. Restart your Streamlit app")
        print("   2. Check the sidebar - you should see 'AI Enhanced Mode'")
        print("   3. Ask a question to test LLM-powered answers!")
    else:
        print("⚠️  No API keys provided. LLM features will not be available.")
        print("   The bot will work in 'Basic Mode' without LLM.")
    
    print()
    print("=" * 60)

if __name__ == "__main__":
    try:
        setup_llm()
    except KeyboardInterrupt:
        print("\n\n❌ Setup cancelled.")
    except Exception as e:
        print(f"\n\n❌ Error: {e}")

